### PR TITLE
isFatal and asych

### PR DESCRIPTION
**Pull request by golanha**
This change is [Reviewable](https://reviewable.io/reviews/kube-hpc/etcd.hkube/36)

### CODE REVIEW

**Review by yehiyam — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/etcd.hkube/36)* status: all files reviewed, 2 unresolved discussions (waiting on @golanha)

___
*[lib/core/client.js, line 67 at r1](https://reviewable.io/reviews/kube-hpc/etcd.hkube/36#-MxDdosPBKyQhqewPWjT:-MxDdosPBKyQhqewPWjU:bt8ovoa) ([raw file](https://github.com/kube-hpc/etcd.hkube/blob/b09f884c172ff76df01182b7ec0ba5360f90ae17/lib/core/client.js#L67)):*
> ```JavaScript
>     }
> 
>     isFatal(err) {
> ```

Add unittest
___
*[lib/layout/discovery/discovery.js, line 25 at r1](https://reviewable.io/reviews/kube-hpc/etcd.hkube/36#-MxDi-p85IAb7835NIjt:-MxDi-p85IAb7835NIju:b6zqpui) ([raw file](https://github.com/kube-hpc/etcd.hkube/blob/b09f884c172ff76df01182b7ec0ba5360f90ae17/lib/layout/discovery/discovery.js#L25)):*
> ```JavaScript
>     }
> 
>     async set(option) {
> ```

Why do you need to add async here? and if you need, why not in delete, register, and all other methods.
Is it so you will know to await the result in the wrapper?
I think it will be better to wrap the methods in state-manager.js and not the low level methods.

**Review by golanha — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/etcd.hkube/36)* status: 1 of 6 files reviewed, 2 unresolved discussions (waiting on @yehiyam)

___
*[lib/core/client.js, line 67 at r1](https://reviewable.io/reviews/kube-hpc/etcd.hkube/36#-MxDdosPBKyQhqewPWjT:-MxEy22e0uXETDYYDN9R:b-896fix) ([raw file](https://github.com/kube-hpc/etcd.hkube/blob/b09f884c172ff76df01182b7ec0ba5360f90ae17/lib/core/client.js#L67)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

Add unittest
</blockquote></details>

Done.
___
*[lib/layout/discovery/discovery.js, line 25 at r1](https://reviewable.io/reviews/kube-hpc/etcd.hkube/36#-MxDi-p85IAb7835NIjt:-MxEy34sEOzYxGPlxzRE:b-896fix) ([raw file](https://github.com/kube-hpc/etcd.hkube/blob/b09f884c172ff76df01182b7ec0ba5360f90ae17/lib/layout/discovery/discovery.js#L25)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

Why do you need to add async here? and if you need, why not in delete, register, and all other methods.
Is it so you will know to await the result in the wrapper?
I think it will be better to wrap the methods in state-manager.js and not the low level methods. 
</blockquote></details>

Done.

**Review by yehiyam — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/etcd.hkube/36)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @golanha and @yehiyam)

___
*[tests/test.js, line 8 at r2](https://reviewable.io/reviews/kube-hpc/etcd.hkube/36#-MxTYImT51JR_BZb6YaJ:-MxTYImT51JR_BZb6YaK:b-9q54b5) ([raw file](https://github.com/kube-hpc/etcd.hkube/blob/27ff3df1e4b8f6ea8cd49b7ed62a73cf435b2dc5/tests/test.js#L8)):*
> ```JavaScript
> const triggersTreeExpected = require('./mocks/triggers-tree.json');
> const Semaphore = require('await-done').semaphore;
> const { ExecuteWrapper } = require('cockatiel/dist/common/Executor');
> ```

not used



_Code quote:_
```JavaScript
 ExecuteWrapper
```

**Review by yehiyam — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/etcd.hkube/36)* status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @golanha and @yehiyam)

___
*[tests/test.js, line 2431 at r2](https://reviewable.io/reviews/kube-hpc/etcd.hkube/36#-MxTYMvk9gxp_ZRbNMyn:-MxTYMvk9gxp_ZRbNMyo:b-rmirai) ([raw file](https://github.com/kube-hpc/etcd.hkube/blob/27ff3df1e4b8f6ea8cd49b7ed62a73cf435b2dc5/tests/test.js#L2431)):*
> ```JavaScript
>         describe('isFatal', () => {
>             it('return isFatal true on etcd problem', async () => {
>                 const { GRPCGenericError, EtcdError } = require('etcd3');
> ```

why not require it at the top?

**Review by yehiyam — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/etcd.hkube/36)* status: 5 of 6 files reviewed, 3 unresolved discussions (waiting on @golanha and @yehiyam)

___
*[tests/test.js, line 2431 at r2](https://reviewable.io/reviews/kube-hpc/etcd.hkube/36#-MxTYVRl6U05UCJl2d48:-MxTYVRl6U05UCJl2d49:b-d334nv) ([raw file](https://github.com/kube-hpc/etcd.hkube/blob/27ff3df1e4b8f6ea8cd49b7ed62a73cf435b2dc5/tests/test.js#L2431)):*
> ```JavaScript
>         describe('isFatal', () => {
>             it('return isFatal true on etcd problem', async () => {
>                 const { GRPCGenericError, EtcdError } = require('etcd3');
> ```

required but not used



_Code quote:_
```JavaScript
EtcdError
```

**Review by golanha — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/etcd.hkube/36)* status: 5 of 6 files reviewed, 3 unresolved discussions (waiting on @yehiyam)

___
*[tests/test.js, line 8 at r2](https://reviewable.io/reviews/kube-hpc/etcd.hkube/36#-MxTYImT51JR_BZb6YaJ:-MxTZDM-6enJ2CgzQVBK:b-896fix) ([raw file](https://github.com/kube-hpc/etcd.hkube/blob/27ff3df1e4b8f6ea8cd49b7ed62a73cf435b2dc5/tests/test.js#L8)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

not used
</blockquote></details>

Done.
___
*[tests/test.js, line 2431 at r2](https://reviewable.io/reviews/kube-hpc/etcd.hkube/36#-MxTYMvk9gxp_ZRbNMyn:-MxTZRPN2KVr18L_fezQ:b-896fix) ([raw file](https://github.com/kube-hpc/etcd.hkube/blob/27ff3df1e4b8f6ea8cd49b7ed62a73cf435b2dc5/tests/test.js#L2431)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

why not require it at the top?
</blockquote></details>

Done.



_Code quote:_
```JavaScript
const { GRPCGenericError, EtcdError } = require('etcd3');
```
___
*[tests/test.js, line 2431 at r2](https://reviewable.io/reviews/kube-hpc/etcd.hkube/36#-MxTYVRl6U05UCJl2d48:-MxTZTlCAc9eyFbpcNXz:b-896fix) ([raw file](https://github.com/kube-hpc/etcd.hkube/blob/27ff3df1e4b8f6ea8cd49b7ed62a73cf435b2dc5/tests/test.js#L2431)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

required but not used
</blockquote></details>

Done.

**Review by yehiyam — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/etcd.hkube/36#-:-MxTaSFRC0_3Yfc5cP08:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @golanha)

**Pull request merged**
