### PR TITLE
keysOnly and count

### PR DESCRIPTION
**Pull request by yehiyam**
add keysOnly option to list
add count method

---
This change is [Reviewable](https://reviewable.io/reviews/kube-hpc/etcd.hkube/20)

### CODE REVIEW

**Review by NassiHarel — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/etcd.hkube/20)* status: all files reviewed, 5 unresolved discussions (waiting on @yehiyam)

___
*[lib/core/etcd-client.js, line 66 at r1](https://reviewable.io/reviews/kube-hpc/etcd.hkube/20#-MJ6BngP2BET1KSGB_wJ:-MJ6BngQ3Uvecf3FIdyl:b930tu8) ([raw file](https://github.com/kube-hpc/etcd.hkube/blob/72a667acc7b717c7bbfe0ff822f9305ac00eb381/lib/core/etcd-client.js#L66)):*
> ```
>   .keys();
> ```
I think that `keys` is actually fetching the data and then map over it.
What you want is `count`.
You can add a new function called `keys`.
___
*[lib/core/service.js, line 120 at r1](https://reviewable.io/reviews/kube-hpc/etcd.hkube/20#-MJ6CRNkCfX_g34NwucF:-MJ6CRNkCfX_g34NwucG:b-j1yj5h) ([raw file](https://github.com/kube-hpc/etcd.hkube/blob/72a667acc7b717c7bbfe0ff822f9305ac00eb381/lib/core/service.js#L120)):*
> ```
> keysOnly: true });
> ```
Maybe `countOnly`?
Add another function `keys`?
___
*[lib/core/service.js, line 132 at r1](https://reviewable.io/reviews/kube-hpc/etcd.hkube/20#-MJ6DVSj6SsnRK6O4LJI:-MJ6DVSj6SsnRK6O4LJJ:b-u0wa40) ([raw file](https://github.com/kube-hpc/etcd.hkube/blob/72a667acc7b717c7bbfe0ff822f9305ac00eb381/lib/core/service.js#L132)):*
> ```
> if (options?.keysOnly || options?.countOnly)   :-)
> ```
___
*[lib/helpers/query-parser.js, line 19 at r1](https://reviewable.io/reviews/kube-hpc/etcd.hkube/20#-MJ6Dh-C4btDyi4TEJLU:-MJ6Dh-C4btDyi4TEJLV:b-8x55ys) ([raw file](https://github.com/kube-hpc/etcd.hkube/blob/72a667acc7b717c7bbfe0ff822f9305ac00eb381/lib/helpers/query-parser.js#L19)):*
> ```
> keysOnly, countOnly :-)
> ```
___
*[lib/helpers/query-schema.js, line 20 at r1](https://reviewable.io/reviews/kube-hpc/etcd.hkube/20#-MJ6Do9DD_YkCgFESsU9:-MJ6Do9DD_YkCgFESsUA:bey5xus) ([raw file](https://github.com/kube-hpc/etcd.hkube/blob/72a667acc7b717c7bbfe0ff822f9305ac00eb381/lib/helpers/query-schema.js#L20)):*
<details><summary><i alt="summary">Quoted 8 lines of code…</i></summary>

> ```
> keysOnly: {
>             type: 'boolean',
>             default: false
>  },
> countOnly: {
>             type: 'boolean',
>             default: false
>   }
> ```
</details>

**Review by yehiyam — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/etcd.hkube/20)* status: 4 of 6 files reviewed, 5 unresolved discussions (waiting on @NassiHarel)

___
*[lib/core/etcd-client.js, line 66 at r1](https://reviewable.io/reviews/kube-hpc/etcd.hkube/20#-MJ6BngP2BET1KSGB_wJ:-MJ6Fu_G0v2nqkpneAtc:b-scc5fu) ([raw file](https://github.com/kube-hpc/etcd.hkube/blob/72a667acc7b717c7bbfe0ff822f9305ac00eb381/lib/core/etcd-client.js#L66)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
>   .keys();
> ```
I think that `keys` is actually fetching the data and then map over it.
What you want is `count`.
You can add a new function called `keys`.
</blockquote></details>

keys should return just the keys (according to the etcd api). but I noticed that there is also count api, so I will use it
___
*[lib/core/service.js, line 120 at r1](https://reviewable.io/reviews/kube-hpc/etcd.hkube/20#-MJ6CRNkCfX_g34NwucF:-MJ6JZrI2FaOwLDWbQ34:b-is0v74) ([raw file](https://github.com/kube-hpc/etcd.hkube/blob/72a667acc7b717c7bbfe0ff822f9305ac00eb381/lib/core/service.js#L120)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> keysOnly: true });
> ```
Maybe `countOnly`?
Add another function `keys`?

</blockquote></details>

Used count method
___
*[lib/core/service.js, line 132 at r1](https://reviewable.io/reviews/kube-hpc/etcd.hkube/20#-MJ6DVSj6SsnRK6O4LJI:-MJ6JiB62JCaxbH18STE:bc47iau) ([raw file](https://github.com/kube-hpc/etcd.hkube/blob/72a667acc7b717c7bbfe0ff822f9305ac00eb381/lib/core/service.js#L132)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> if (options?.keysOnly || options?.countOnly)   :-)
> ```
</blockquote></details>

This is just for keys
___
*[lib/helpers/query-parser.js, line 19 at r1](https://reviewable.io/reviews/kube-hpc/etcd.hkube/20#-MJ6Dh-C4btDyi4TEJLU:-MJ6Jlfl-vZw7nk8OdCn:b-896fix) ([raw file](https://github.com/kube-hpc/etcd.hkube/blob/72a667acc7b717c7bbfe0ff822f9305ac00eb381/lib/helpers/query-parser.js#L19)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> keysOnly, countOnly :-)
> ```

</blockquote></details>

Done.
___
*[lib/helpers/query-schema.js, line 20 at r1](https://reviewable.io/reviews/kube-hpc/etcd.hkube/20#-MJ6Do9DD_YkCgFESsU9:-MJ6JqFJ7VxhI3Fih4Md:b-896fix) ([raw file](https://github.com/kube-hpc/etcd.hkube/blob/72a667acc7b717c7bbfe0ff822f9305ac00eb381/lib/helpers/query-schema.js#L20)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> keysOnly: {
>             type: 'boolean',
>             default: false
>  },
> countOnly: {
>             type: 'boolean',
>             default: false
>   }
> ```

</blockquote></details>

Done.

**Review by NassiHarel — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/etcd.hkube/20)* status: all files reviewed, 6 unresolved discussions (waiting on @NassiHarel and @yehiyam)

___
*[lib/core/etcd-client.js, line 65 at r2](https://reviewable.io/reviews/kube-hpc/etcd.hkube/20#-MJ6Lmms0WIGPWtl6r51:-MJ6Lmms0WIGPWtl6r52:b-mfxf3z) ([raw file](https://github.com/kube-hpc/etcd.hkube/blob/4ee1720112fc37e066f26bbd34c7e84737939267/lib/core/etcd-client.js#L65)):*
> ```
> if (keysOnly)
> ```
This `keysOnly` is unused :-( but you can find 8 instances of it in the code.
You can add `keys` method or remove it...

**Review by yehiyam — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/etcd.hkube/20)* status: 3 of 6 files reviewed, 6 unresolved discussions (waiting on @NassiHarel)

___
*[lib/core/etcd-client.js, line 66 at r1](https://reviewable.io/reviews/kube-hpc/etcd.hkube/20#-MJ6BngP2BET1KSGB_wJ:-MJ6YWgP4i9TCMR0GB1F:b-896fix) ([raw file](https://github.com/kube-hpc/etcd.hkube/blob/72a667acc7b717c7bbfe0ff822f9305ac00eb381/lib/core/etcd-client.js#L66)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

keys should return just the keys (according to the etcd api). but I noticed that there is also count api, so I will use it
</blockquote></details>

Done.
___
*[lib/core/etcd-client.js, line 65 at r2](https://reviewable.io/reviews/kube-hpc/etcd.hkube/20#-MJ6Lmms0WIGPWtl6r51:-MJ6YVn940k6b-1sA7of:b-896fix) ([raw file](https://github.com/kube-hpc/etcd.hkube/blob/4ee1720112fc37e066f26bbd34c7e84737939267/lib/core/etcd-client.js#L65)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> if (keysOnly)
> ```
This `keysOnly` is unused :-( but you can find 8 instances of it in the code.
You can add `keys` method or remove it...
</blockquote></details>

Done.
___
*[lib/core/service.js, line 120 at r1](https://reviewable.io/reviews/kube-hpc/etcd.hkube/20#-MJ6CRNkCfX_g34NwucF:-MJ6YXgm7jYJtb3r52Tk:b-896fix) ([raw file](https://github.com/kube-hpc/etcd.hkube/blob/72a667acc7b717c7bbfe0ff822f9305ac00eb381/lib/core/service.js#L120)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

Used count method
</blockquote></details>

Done.
___
*[lib/core/service.js, line 132 at r1](https://reviewable.io/reviews/kube-hpc/etcd.hkube/20#-MJ6DVSj6SsnRK6O4LJI:-MJ6YYA9-TYwbWL484_c:b-896fix) ([raw file](https://github.com/kube-hpc/etcd.hkube/blob/72a667acc7b717c7bbfe0ff822f9305ac00eb381/lib/core/service.js#L132)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

This is just for keys
</blockquote></details>

Done.

**Review by NassiHarel — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/etcd.hkube/20#-:-MJ6engF7hFNETkgYbbd:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
